# Generated by Django 5.2.17 on 2026-09-04 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of guest or family group', max_length=200)),
                ('side', models.CharField(choices=[('alex', 'Alex'), ('divya', 'Divya')], default='divya', max_length=20)),
                ('relationship', models.CharField(choices=[('divya', 'Divya'), ('daisy', 'Daisy'), ('davis', 'Davis'), ('diya', 'Diya'), ('alex', 'Alex')], default='divya', help_text='Primary relationship connection', max_length=20)),
                ('guest_count', models.PositiveIntegerField(default=1, help_text='Number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('events_invited', models.CharField(choices=[('all', 'All Events (Engagement & Wedding)'), ('engagement', 'Engagement Only'), ('wedding', 'Wedding Only')], default='all', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invitee',
                'verbose_name_plural': 'Invitees',
                'ordering': ['name'],
            },
        ),
    ]
